### ISSUE TITLE
Resources saved to res:// at runtime get reverted: Can't save SaveGame to res:// reliably

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-open-rpg#159]

**Comment by NathanLovato** [comment]
According to @nhydock this is due to a bug in the engine: saving Resources to `res://` while the game is running seems to not work as expected, but saving to the `user://` dir works no problem. But if we can only save to `user://` it kills one of the main points of using resources: being able to edit the savegame in the inspector

**Comment by nhydock** [comment]
godotengine/godot#24646 highlights the same issue we're having

**Comment by asheraryam** [comment]
In this case wouldn't the best course of action would be to save resources to user:// after they are changed, and when loading check if they exist in user:// or else default to res:// ?

**Comment by NathanLovato** [comment]
@asheraryam The point was to save debug save files in res:// so we can edit them in the inspector
