### ISSUE TITLE
Display rewards gained from quests

### ISSUE THREAD

**Issue by guilhermehto** [GDQuest/godot-open-rpg#164]
Even though the player can use the quest journal to see what the rewards are, there's nothing visual that show him what he got when he finishes a quest. 

Depends on #163

**Comment by NathanLovato** [comment]
Removing from the 0.4 milestone, we've got a lot of stuff to do on other projects and my gut feeling is that the questsystem will need to change once we start to have real content, so I don't want us to push it too much now
