### ISSUE TITLE
Duplicating Visual Script node loses custom script reference

### ISSUE THREAD

**Issue by TheRealCatherine** [GDquest/godot-open-rpg#188]
Steps to reproduce:

1) Create a custom node type using GD script
2) Add a "Custom Node" to a new Visual Script
3) Set the type to your custom node using Reference/Script thing in the Inspector
4) Press Ctrl-D to duplicate your node
5) Notice Script only shows a gear
(if you then click the blank Script reference in the Inspector you get into some weird stuff that seems to break some things and sometimes leads to crashes)

Original Custom Node:
![image](https://user-images.githubusercontent.com/31754592/55885144-0121ca80-5b6f-11e9-8880-ba3f06e96e9d.png)

Duplicate Node:
![image](https://user-images.githubusercontent.com/31754592/55885166-10087d00-5b6f-11e9-8963-c5b9413dcb3c.png)

**Comment by NathanLovato** [comment]
Does this have to do with this game project? We're not using visual scripting at all.

**Comment by TheRealCatherine** [comment]
no I'm sorry I meant to file it on the Godot project wrong tab

**Comment by TheRealCatherine** [comment]
Ok that is now https://github.com/godotengine/godot/issues/27897
in case anyone comes across this report looking for that one.
