### ISSUE TITLE
Resources broken when project is exported to an .exe

### ISSUE THREAD

**Issue by youreperfect** [GDQuest/godot-open-rpg#189]
Using Godot 3.1-stable-win64

The DialogDatabase which loads .tres files at application startup does not work for exported (aka built/compiled) projects - the .tres files are either not included in the export (or are not accessible in the same way) leading to

![image](https://user-images.githubusercontent.com/49788602/56624475-9fe20880-65fe-11e9-9e99-88821242f9f8.png)

It works fine when running in the editor - just not in an exported build

**Comment by youreperfect** [comment]
There are a apparently a whole series of bugs in Godot related to this and debate over how or if to fix it - for example: https://github.com/godotengine/godot/issues/25672

**Comment by NathanLovato** [comment]
Thanks! I don't have time to look into it now, I'll leave a help wanted label for now

**Comment by kedodrill** [comment]
Just an update to this - after exporting my game using a C# implementation of the Dialogue system, it would not load characters.

Looks like someone is mentioning here that the Directory system should not be used for this...although dynamically loading the resources would be preferred imo I'm not sure who is right...

https://github.com/godotengine/godot-docs/issues/2280
