### ISSUE TITLE
One gray pixel line appear on tiles, when the camara moves

### ISSUE THREAD

**Issue by MateoMiccino** [GDquest/godot-open-rpg#190]
I'm working on Ubuntu 16.04.06 64bits
I test it with the editor, and compiled version, and still the result is the same

![image](https://user-images.githubusercontent.com/12563266/60287648-c8c99700-98e8-11e9-9cb7-5c66beb87cba.png)
![image](https://user-images.githubusercontent.com/12563266/60287662-d0893b80-98e8-11e9-8167-dea5fa68e85f.png)
![image](https://user-images.githubusercontent.com/12563266/60287681-d717b300-98e8-11e9-9b04-3e1e294528e6.png)

**Comment by Zireael07** [comment]
Your GFX card?

**Comment by MateoMiccino** [comment]
OpenGL ES 3.0 Renderer: GeForce GTX 960/PCIe/SSE2

When i enable "Use Pixel Snap" (Projects > Project Settings > Quality > 2D > Pixel Snap" it's work perfectly.

I making a PR for this.
