### ISSUE TITLE
DialogueCombatPawn loops dialogue if Enter key is pressed

### ISSUE THREAD

**Issue by rcjsuen** [GDQuest/godot-open-rpg#206]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

If the <kbd>Enter</kbd> key is used to advance the dialogue with `DialogueCombatPawn`, it will cycle forever.

**What is the current behavior?**
After "Done" the dialogue will go back to "Next" instead of going into combat.

**What is the expected behavior?**
After "Done" we should enter combat.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Start the game.
2. Move east to the arrow directly east of the player.
3. The exclamation mark hover will appear when the player is next to`DialogueCombatPawn`.
4. Hit <kbd>Enter</kbd> to start the dialogue.
5. Repeatedly hit <kbd>Enter</kbd> to notice that the dialogue just loops now.

**Comment by godofgrunts** [comment]
Located the bug in `PawnInteractive.gd`.

`if event.is_action_pressed("ui_accept") and dialogue_balloon.visible:` triggers every time you press `ui_accept` (but only for keyboard inputs, not clicks).

Adding `set_process_unhandled_input(false) ` at the end of the if statement fixes it, but it doesn't allow you to interact with the map event again which probably isn't the desired outcome.

What really confuses me is that I feel like that check should be `if event.is_action_pressed("ui_accept") and dialogue_balloon.visible == false:`

If you do that than something really strange happens where the quest system gets processed. Pressing `space` twice gives you the test quest and starts the battle with no dialogue box showing. There's something weird going on, but I can't currently track it down.
