### ISSUE TITLE
SkillAction: When the skill misses, show a "miss" animation/label pop up

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-open-rpg#89]

**Comment by godofgrunts** [comment]
This probably could be combined with a status effect label if you wanted to use words for status effects (as opposed to sprites). But if you wanted to separate them (or maybe just have both) I don't think it adds that much complexity.

Probably should rename and `PopUpLabel` if we're going to separate them.

Not sure how you would want to go about that. Something like:

`PopUpLabelInt.tscn`
`PopUpLabelText.tscn`
`PopUpSprite.tscn`

And in `PopUpBuilder.gd` we should change `func spawn_label` to something like `func spawn_label_int` and make two more that are `spawn_label_text` and `spawn_sprite`.

**Comment by NathanLovato** [comment]
It's a little abstract to me right now, I'm not sure what you would be trying to achieve with this setup. 
If you want to reuse the animations as resources between the nodes, they can't have different names.

Right now the element that comes up over the character is an animated control node. 
You could have anything as a child of it, use aggregation instead of separate base scenes to animate different elements popping up on top of a character.

Regarding localization, let's at least wait until we have the base game's design in place and words or sentences to translate. It's not a problem to add it later.

**Comment by henriiquecampos** [comment]
@godofgrunts I think you can leave with just a single animation and just have a child, hidden, for each scenario, so a child for Miss, another for Stun, another for Damage, another for Healing, Mana...and show/hide them depending on what will be displayed. Since the animation itself will be on the parent, all of its children will be animated as well.
