### ISSUE TITLE
Anim: modular Robi battler anim and test animation

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-open-rpg#94]
The sprites are more or less ready but I need to test the animation setup and rigging and Godot 3.1, see if it's working already:

Test animations:

1. Idle
2. Attack

**Comment by GraphicEdit** [comment]
![test-anim](https://user-images.githubusercontent.com/1042534/49939656-573e7400-fed5-11e8-9a5a-b9b07026d596.gif)

can we use anim for  characters?
